# Generated by Django 2.1 on 2018-08-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
