# Generated by Django 2.1 on 2018-08-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0005_auto_20180826_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='tweet',
        ),
    ]
