# Generated by Django 2.1 on 2018-08-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0006_auto_20180826_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
